### ISSUE TITLE
Task module not found error

### ISSUE THREAD

**Issue by shoaibb** [eyalzh/simple-kanban#1]
Everything worked perfect on Mint Linux 19.1 except for the error "TS2307: Cannot find module '../model/task'."

After proper debugging, I found that the problem is in one line in both these files:

file 1) /simple-kanban/src/components/ColumnComponent.tsx 
Error line: import {Task, TaskPresentationalOptions} from "../model/task";

file 2) /simple-kanban/src/components/TaskComponent.tsx
Error line: import {Task} from "../model/task";

Solution for both errors: Change ../model/task to ../model/Task

**Comment by eyalzh** [comment]
Thanks! Fixed in 45f7a8d345425534046092b3e9e4743f3413fc85
